// tools/extract-js.mjs — SESSION 2 Step 1.
//
// Splits the SPA's single inline <script> into four modules. Function bodies are
// sliced VERBATIM by line range out of the original — this file never retypes them.
// Only two categories of change are applied, both logged:
//
//   BIND  a top-level `$("#x").addEventListener(...)` becomes `on("#x", ...)`, a
//         helper that no-ops when the element is absent. Needed because each page
//         now carries only its own markup, and the original bindings assume every
//         view exists in the DOM.
//   LINK  `onclick="openModal(BOOKS[i])"` becomes a real <a href="/book/{slug}">.
//         The modal is retired in SESSION 2 — the book page is its replacement.
//
// Deleted outright (SESSION 2 Step 1 + Step 8):
//   probeImg / lookupCover / applyCover / resolveCoverContainer / coverObserver /
//   observeCovers / tfetch / gbPick / olISBN / coverCache   — the speculative cover
//     probe and its Open Library + Google Books fallback chain. The build knows
//     which covers exist.
//   lookupFace / faceCache / faceObserver / hydrateFace / observeFaces / avatarHTML /
//   SIL / normAuthorMap / renderAuthors / renderAuthorBatch / openAuthor /
//   closeAuthor / booksByAuthor            — the Authors view, removed entirely.
//   showView / readState / writeState / activeView / ensureView / gotoTheme /
//   gotoYear / gotoYearReview / dataError / bootstrap   — SPA hash routing, replaced
//     by real URLs.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src/assets/js');

const html = fs.readFileSync(path.join(ROOT, 'src/index.html'), 'utf8');
const js = /<script>\n?([\s\S]*?)<\/script>/.exec(html)[1];
const L = js.split('\n');

/** Slice by 1-indexed inclusive start .. exclusive end, exactly as mapped. */
const cut = (a, b) => L.slice(a - 1, b - 1).join('\n');

const log = [];
function patch(src, find, replace, label) {
  const n = src.split(find).length - 1;
  if (n === 0) { console.error(`✗ patch "${label}" matched nothing`); process.exit(1); }
  log.push(`  ${label} (${n}×)`);
  return src.split(find).join(replace);
}

// ---------------------------------------------------------------- shared prelude
const PRELUDE = `/* GENERATED by tools/extract-js.mjs — DO NOT EDIT.
   Source: the inline <script> in src/index.html. Function bodies are verbatim. */
`;

const HELPERS = `
const $ = (s) => document.querySelector(s);
const $$ = (s) => document.querySelectorAll(s);

/* Guarded binding. The original script bound straight to elements at the top level,
   which is safe in a single-page app where every view is in the DOM and fatal on a
   generated page that only carries its own markup. */
function on(sel, ev, fn, opts) {
  const el = typeof sel === 'string' ? $(sel) : sel;
  if (el) el.addEventListener(ev, fn, opts);
  return !!el;
}

/* Data loading. Nothing here runs before first paint — every page is server-rendered
   and these are fetched only when an interactive feature actually needs them. */
let BOOKS = [], ID2I = {}, EDGES = [], SLUGS = {};
let _dataPromise = null;
function loadBooks() {
  if (_dataPromise) return _dataPromise;
  _dataPromise = Promise.all([
    fetch('/books.json', { cache: 'no-cache' }).then((r) => r.json()),
    fetch('/data/slugs.json', { cache: 'no-cache' }).then((r) => r.json()).catch(() => ({})),
    fetch('/data/titles.json', { cache: 'no-cache' }).then((r) => r.json()).catch(() => ({})),
  ]).then(([data, slugs, titles]) => {
    BOOKS = data.books || [];
    EDGES = data.edges || [];
    SLUGS = slugs || {};
    ID2I = {};
    BOOKS.forEach((b, i) => {
      ID2I[b.id] = i;
      // Title bridge — see WORKER-TITLE-FIX.md. Empty once the sync is fixed.
      if (!String(b.title || '').trim() && titles[b.id]) b.title = titles[b.id];
    });
    return BOOKS;
  });
  return _dataPromise;
}
function bookHref(id) { return SLUGS[id] ? '/book/' + SLUGS[id] : '/library'; }
`;

// ---------------------------------------------------------------- app.js
let app = PRELUDE + HELPERS + [
  cut(22, 30),      // STANDOUTS + STANDOUT_OF
  cut(31, 42),      // shade, esc, fmtText, num, THEME_COLORS, THEME_ORDER
  cut(42, 43),      // phHTML
  cut(87, 89),      // byDateDesc
  cut(93, 98),      // toggleMenu, closeMenu
  cut(350, 353),    // YEAR_ORDER, ybucket
  cut(353, 357),    // TIP + tipShow/tipMove/tipHide
  cut(357, 358),    // fmtDate
  cut(358, 387),    // list/book popovers + hideAllPops + window bindings
  cut(387, 391),    // bindList, bindTip
  cut(475, 481),    // mtImgErr
  cut(589, 599),    // yirCover, yirImgErr, observeYirCovers
  cut(599, 607),    // gcImgErr
  cut(664, 673),    // tgImgErr, tgCover
  cut(727, 728),    // median
  cut(1053, 1074),  // copyBookLink, fallbackCopy
  cut(1153, 1222),  // escRe, hl, snippet, searchBooks, runSearch, openSearch, closeSearch
  cut(1222, 1230),  // _srT + search bindings
  cut(1230, 1273),  // REC_ENDPOINT, openRec, closeRec, recommend-form IIFE
].join('\n');

// TIP is `const TIP=$("#tip"),TIPT=TIP.querySelector(...)` — throws where #tip is absent.
app = patch(app,
  'const TIP=$("#tip"),TIPT=TIP.querySelector(".tt"),TIPS=TIP.querySelector(".ts");',
  'const TIP=$("#tip"),TIPT=TIP&&TIP.querySelector(".tt"),TIPS=TIP&&TIP.querySelector(".ts");',
  'BIND tooltip element guard');
app = patch(app, 'function tipShow(e,title,sub){TIPT.textContent',
  'function tipShow(e,title,sub){if(!TIP)return;TIPT.textContent', 'BIND tipShow guard');
app = patch(app, 'function tipMove(e){TIP.style.left', 'function tipMove(e){if(!TIP)return;TIP.style.left', 'BIND tipMove guard');
app = patch(app, 'function tipHide(){TIP.classList.remove("show");}',
  'function tipHide(){if(TIP)TIP.classList.remove("show");}', 'BIND tipHide guard');
app = patch(app, 'function showListPop(e,title,sub,books){\n  const lp=$("#listpop");',
  'function showListPop(e,title,sub,books){\n  const lp=$("#listpop"); if(!lp)return;', 'BIND showListPop guard');
app = patch(app, 'function moveListPop(e){const lp=$("#listpop");',
  'function moveListPop(e){const lp=$("#listpop"); if(!lp)return;', 'BIND moveListPop guard');
app = patch(app, 'function hideListPop(){$("#listpop").classList.remove("show");}',
  'function hideListPop(){const lp=$("#listpop"); if(lp)lp.classList.remove("show");}', 'BIND hideListPop guard');
app = patch(app, 'function showBookPop(e,bi){const b=BOOKS[bi];if(!b)return;const bp=$("#bookpop");',
  'function showBookPop(e,bi){const b=BOOKS[bi];if(!b)return;const bp=$("#bookpop"); if(!bp)return;', 'BIND showBookPop guard');
app = patch(app, 'function moveBookPop(e){const bp=$("#bookpop");',
  'function moveBookPop(e){const bp=$("#bookpop"); if(!bp)return;', 'BIND moveBookPop guard');
app = patch(app, 'function hideBookPop(){$("#bookpop").classList.remove("show");}',
  'function hideBookPop(){const bp=$("#bookpop"); if(bp)bp.classList.remove("show");}', 'BIND hideBookPop guard');

// Search results linked to book pages instead of opening the retired modal.
app = patch(app,
  '<div class="sr-item" onclick="closeSearch();openModal(BOOKS[${ID2I[b.id]}])">',
  '<a class="sr-item" href="${bookHref(b.id)}">',
  'LINK search result -> /book/{slug}');
app = patch(app, '        <div class="sr-where">matched in ${where.join(" \\u00b7 ")}</div>\n      </div>\n    </div>`;',
  '        <div class="sr-where">matched in ${where.join(" \\u00b7 ")}</div>\n      </div>\n    </a>`;',
  'LINK search result close tag');
app = patch(app, '$("#searchModal").addEventListener("click",e=>{if(e.target.id==="searchModal")closeSearch();});',
  'on("#searchModal","click",e=>{if(e.target.id==="searchModal")closeSearch();});', 'BIND searchModal');
app = patch(app, 'let _srT;$("#searchInput").addEventListener("input",()=>{clearTimeout(_srT);_srT=setTimeout(runSearch,140);});',
  'let _srT;on("#searchInput","input",()=>{clearTimeout(_srT);_srT=setTimeout(runSearch,140);});', 'BIND searchInput');
app = patch(app, 'function openSearch(){const m=$("#searchModal");if(!m)return;m.classList.add("open");runSearch();',
  'function openSearch(){const m=$("#searchModal");if(!m)return;m.classList.add("open");loadBooks().then(runSearch);',
  'lazy-load data on search open');
app = patch(app, 'function runSearch(){\n  const q=$("#searchInput").value.trim();',
  'function runSearch(){\n  const si=$("#searchInput"); if(!si)return;\n  const q=si.value.trim();', 'BIND runSearch guard');

app += `

/* Replaces a cover <img> with the themed placeholder when the file is absent.
   This is the successor to the deleted probeImg chain: one real request per visible
   cover, no speculative probe, and no Open Library / Google Books fallback. */
function phCover(img) {
  const wrap = img.parentNode;
  if (!wrap) return;
  const b = BOOKS[+img.dataset.i];
  wrap.innerHTML = b ? phHTML(b) : '';
}
window.phCover = phCover;

/* Nav toggle for generated pages. */
on('#navToggle', 'click', toggleMenu);

/* The Escape key closed three overlays in the SPA; two of them are retired. */
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape') { closeSearch(); closeRec(); }
  if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); openSearch(); }
});
window.bookHref = bookHref;
window.loadBooks = loadBooks;
`;
// The four *ImgErr handlers each hopped to Open Library before falling back to the
// local placeholder. That hop is part of the third-party chain SESSION 2 Step 1 deletes:
// go straight to the placeholder, no cross-origin request.
app = patch(app,
  '  if(img.dataset.s==="0"&&img.dataset.isbn){img.dataset.s="1";img.src="https://covers.openlibrary.org/b/isbn/"+img.dataset.isbn+"-S.jpg?default=false";return;}\n',
  '  /* Open Library hop removed — placeholder directly. */\n',
  'DELETE Open Library hop from *ImgErr');
app = patch(app,
  '  const cov=b.isbn?`https://covers.openlibrary.org/b/isbn/${b.isbn}-M.jpg?default=false`:"";\n',
  '',
  'DELETE Open Library cover URL in showBookPop');
app = patch(app,
  'function observeYirCovers(){ /* covers resolve via the openlibrary/placeholder fallback chain in yirImgErr */ }',
  'function observeYirCovers(){ /* no-op: covers are plain <img> with a local placeholder on error */ }',
  'DELETE stale Open Library comment');
app = patch(app,
  'bp.innerHTML=`<img class="bpcov" src="/covers/${b.id}.jpg" onerror="this.onerror=null;this.src=\'${cov}\';this.onerror=function(){this.style.visibility=\'hidden\'}">`+',
  'bp.innerHTML=`<img class="bpcov" src="/covers/${b.id}.jpg" width="52" height="78" alt="" loading="lazy" onerror="this.style.visibility=\'hidden\'">`+',
  'DELETE Open Library fallback in showBookPop img');

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'app.js'), app);

// ---------------------------------------------------------------- graph.js
let graph = PRELUDE + [
  cut(1273, 1274),   // let G=null
  cut(1274, 1460),   // initGraph — the force simulation, verbatim
].join('\n');
graph = patch(graph, 'if(!G.moved){openModal(BOOKS[dragging.i]);}', 'if(!G.moved){location.href=bookHref(BOOKS[dragging.i].id);}', 'LINK graph node click (mouse)');
graph = patch(graph, 'if(!G.moved)openModal(BOOKS[dragging.i]);', 'if(!G.moved)location.href=bookHref(BOOKS[dragging.i].id);', 'LINK graph node click (touch)');
graph = patch(graph, 'const canvas=$("#graphCanvas"), ctx=canvas.getContext("2d");',
  'const canvas=$("#graphCanvas"); if(!canvas)return; const ctx=canvas.getContext("2d");', 'BIND graph canvas guard');
graph = patch(graph, 'window.addEventListener("resize",()=>{if($("#view-connections").classList.contains("active")){DPR=Math.min(window.devicePixelRatio||1,2);size();}});',
  'window.addEventListener("resize",()=>{DPR=Math.min(window.devicePixelRatio||1,2);size();});', 'BIND graph resize (no view container)');
graph += fs.readFileSync(path.join(ROOT, 'tools/js-parts/graph-extra.js'), 'utf8');
fs.writeFileSync(path.join(OUT, 'graph.js'), graph);

// ---------------------------------------------------------------- analytics.js
let analytics = PRELUDE + [
  cut(391, 399),     // tyMetric, renderTime
  cut(399, 428),     // renderYearStack
  cut(428, 429),     // mtMetric
  cut(429, 475),     // renderMonthTrend, bindMonthPop
  cut(481, 505),     // showMonthPop + mt/ty toggles
  cut(505, 589),     // renderYearReview
  cut(607, 626),     // sdRows, stackDetail, stackDetailDefault
  cut(626, 663),     // renderProfile
  cut(709, 736),     // WD..LENS, lensList, v0, deltaHTML
  cut(736, 812),     // renderAnalytics
  cut(812, 815),     // lensAuthorCounts, lensBuilt
  cut(815, 832),     // buildLensOptions
  cut(832, 833),     // periodBooks
  cut(833, 851),     // renderCompare
  cut(851, 893),     // renderThemeDyn
  cut(893, 910),     // renderCrosstab
  cut(910, 927),     // renderRecords
  cut(927, 1005),    // renderHeatmap, renderHeatMonths, renderHeatDays
  cut(1005, 1053),   // paceGran, renderPace + paceToggle binding
].join('\n');

for (const [find, replace, label] of [
  ['$("#mtToggle").addEventListener("click",', 'on("#mtToggle","click",', 'BIND mtToggle'],
  ['$("#tyToggle").addEventListener("click",', 'on("#tyToggle","click",', 'BIND tyToggle'],
  ['$("#paceToggle").addEventListener("click",', 'on("#paceToggle","click",', 'BIND paceToggle'],
  ['$("#lensYear").addEventListener("change",', 'on("#lensYear","change",', 'BIND lensYear'],
  ['$("#lensReset").addEventListener("click",', 'on("#lensReset","click",', 'BIND lensReset'],
  ['$("#cmpA").addEventListener("change",renderCompare);$("#cmpB").addEventListener("change",renderCompare);',
   'on("#cmpA","change",renderCompare);on("#cmpB","change",renderCompare);', 'BIND compare selects'],
]) analytics = patch(analytics, find, replace, label);

// Records, year-review cards and stack detail linked to book pages, not the modal.
analytics = patch(analytics, '<div class="rec" onclick="openModal(BOOKS[${BOOKS.indexOf(r[2])}])">',
  '<a class="rec" href="${bookHref(r[2].id)}">', 'LINK records card');
analytics = patch(analytics, '<div class="rt">${esc(r[2].title.split(":")[0])}</div></div>`).join("");',
  '<div class="rt">${esc(r[2].title.split(":")[0])}</div></a>`).join("");', 'LINK records close tag');
analytics = patch(analytics, '<div class="yir-bk" onclick="openModal(BOOKS[${ID2I[b.id]}])"',
  '<a class="yir-bk" href="${bookHref(b.id)}"', 'LINK year-review book');
analytics = patch(analytics, '<div class="yc-a">${esc(b.author)}</div></div></div>`).join("");',
  '<div class="yc-a">${esc(b.author)}</div></div></a>`).join("");', 'LINK year-review close tag');
analytics = patch(analytics, '<div class="sd-item" onclick="openModal(BOOKS[${ID2I[b.id]}])">',
  '<a class="sd-item" href="${bookHref(b.id)}">', 'LINK stack-detail row');
analytics = patch(analytics, '<span class="si-a">${esc((b.author||"").split(" ").slice(-1)[0])}</span></div>`).join("");',
  '<span class="si-a">${esc((b.author||"").split(" ").slice(-1)[0])}</span></a>`).join("");', 'LINK stack-detail close tag');
analytics = patch(analytics, 'onclick="gotoYear(\'${y}\')"', 'onclick="location.href=\'/${y}\'"', 'LINK year-review see-all');

analytics += '\n\n/* Retired with the SPA hash router. Stubbed so the extracted bodies stay verbatim. */\nfunction writeState(){}\n';
analytics += fs.readFileSync(path.join(ROOT, 'tools/js-parts/analytics-extra.js'), 'utf8');
fs.writeFileSync(path.join(OUT, 'analytics.js'), analytics);

// ---------------------------------------------------------------- library.js
let library = PRELUDE + [
  cut(42, 43),       // phHTML
  cut(86, 87),       // bookCard
  cut(208, 215),     // CHIP_HIDE, renderChips, latestReadId
  cut(215, 240),     // renderBrowse
  cut(240, 262),     // renderActiveFilters
  cut(262, 272),     // clearBrowseFilters, _qT + #q binding
  cut(272, 277),     // sort/reset/chips bindings
  'var activeTheme="", yearFilter="", drill=null, sortMode="dateRead";',
].join('\n');

library = patch(library, '<div class="book${isLatest?\' is-latest\':\'\'}" data-i="${ID2I[b.id]}"',
  '<a class="book${isLatest?\' is-latest\':\'\'}" href="${bookHref(b.id)}" data-i="${ID2I[b.id]}"', 'LINK book card');
library = patch(library, '<div class="a">${esc(b.author)}</div></div></div>`;}',
  '<div class="a">${esc(b.author)}</div></div></a>`;}', 'LINK book card close tag');
for (const [find, replace, label] of [
  ['$("#sortBtns").addEventListener("click",', 'on("#sortBtns","click",', 'BIND sortBtns'],
  ['$("#browseReset").addEventListener("click",', 'on("#browseReset","click",', 'BIND browseReset'],
  ['$("#emptyReset").addEventListener("click",', 'on("#emptyReset","click",', 'BIND emptyReset'],
  ['$("#themeChips").addEventListener("click",', 'on("#themeChips","click",', 'BIND themeChips'],
  ['let _qT;$("#q").addEventListener("input",', 'let _qT;on("#q","input",', 'BIND search input'],
]) library = patch(library, find, replace, label);
// The extracted bodies still call writeState(), the SPA's hash-state writer. Rather than
// editing those bodies, stub it: /library has a real URL and its filter state is
// deliberately not addressable (guardrail 7 — search gets no indexable URL).
library += '\n\n/* Retired with the SPA hash router and the cover probe. Stubbed so the extracted\n   bodies stay verbatim: /library has a real URL, and covers are plain <img> now. */\nfunction writeState(){}\nfunction observeCovers(){}\n';
library += fs.readFileSync(path.join(ROOT, 'tools/js-parts/library-extra.js'), 'utf8');
fs.writeFileSync(path.join(OUT, 'library.js'), library);

// ---------------------------------------------------------------- report
console.log('Patches applied:');
console.log(log.join('\n'));
for (const f of ['app.js', 'graph.js', 'analytics.js', 'library.js']) {
  const p = path.join(OUT, f);
  console.log(`  ${f.padEnd(14)} ${(fs.statSync(p).size / 1024).toFixed(1)} kB`);
}
// Match call/definition syntax, not the words in the comments that explain the deletion.
for (const banned of ['probeImg(', 'lookupCover(', 'covers.openlibrary.org', 'googleapis.com/books', 'lookupFace(']) {
  for (const f of ['app.js', 'graph.js', 'analytics.js', 'library.js']) {
    if (fs.readFileSync(path.join(OUT, f), 'utf8').includes(banned)) {
      console.error(`✗ ${f} still references ${banned}`); process.exit(1);
    }
  }
}
console.log('\n✓ no probeImg / cover-probe chain / author-headshot lookups survive');
